FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN install_packages shairport-sync

COPY start.sh /usr/src/

ENV ALSA_CARD_ID=0
COPY .asoundrc.tmpl .asoundrc.tmpl
RUN 

CMD [ "/bin/sh", "-c" "envsubst < .asoundrc.tmpl > /root/.asoundrc && /usr/src/start.sh || cat /root/.asoundrc" ]
