FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN install_packages shairport-sync gettext

COPY start.sh /usr/src/

ENV ALSA_CARD_ID=0
COPY .asoundrc.tmpl .asoundrc.tmpl
RUN [ "/bin/sh", "-c", "envsubst < .asoundrc.tmpl > /root/.asoundrc || cat /root/.asoundrc" ]

CMD [ "/bin/sh", "/usr/src/start.sh" ]
